# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  pull_request:
  push:

jobs:
  lint_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14, 16, 18 ]

    name: Node ${{ matrix.node }} lint and test

    steps:
    - uses: actions/checkout@v3
    - name: lint
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: pnpm i --frozen-lockfile
    - run: pnpm run lint
    - run: pnpm run test
